name: chemvae310
channels:
  - rdkit
  - conda-forge

dependencies:
  - tensorflow=2.14.0
  - h5py=3.11.0
  - hdf5
  - pandas=1.5.3
  - python=3.10
  - scikit-learn
  - boost
  - rdkit
  - yaml
  - numpy=1.24.0
  - matplotlib



